### ISSUE TITLE
Categories check

### ISSUE THREAD

**Issue by kam642** [Drexel-UHC/NETS#1]
Updates made to the excel file to reflect the mis-matches in coding the tech def and matrix. Stevie to review, edit code as needed.

I also added a worksheet for the hierarchy. Can you check that what are currently auxilliary categories are included in the hierarchy?

[NETS_Catalogue_ 3LTR_Variables_20230323.xlsx](https://github.com/Drexel-UHC/NETS/files/11053815/NETS_Catalogue_.3LTR_Variables_20230323.xlsx)
[Questions Next Steps NETS_20230323.docx](https://github.com/Drexel-UHC/NETS/files/11053814/Questions.Next.Steps.NETS_20230323.docx)

Files are also saved to the server.

**Comment by kam642** [comment]
@stfran22 @JanaHirsch Woo hoo!!! I think the coding is ready to go!!

I need to add the few things to clean up the excel file (matches to MESA and RECVD, some spot check files from RECVD so we don't repeat them in the future. so assigning this back to me.

@sjmelly Are you overseeing the programming part? Maybe start a new project or issue for that so it's not contained under this categories check.

**Comment by kam642** [comment]
@stfran22 @sd-drexel What is the terminology we finally agreed on for the changing to "main" and "auxiliary"? I'm working on updating the excel file and can't remember what we finally agreed on.

**Comment by JanaHirsch** [comment]
In general, I think of the thematic constructs as ones that DO NOT go into anything higher up. Given that, I think I agree with all except:
-Move Renovation to Combination Category (it has stuff above it, right?)
-Move Cultural Destinations to Combination Category? (it has stuff above it, right?)
-MAYBE move Nighttime to Combination Category (it has stuff above it, right?)

**Comment by kam642** [comment]
Renovation is a subset of Disaster-related construction, cleaning, and services - moved to combination category

Cultural is a subset of Cognitive enrichment - moved to combination category

Nighttime is NOT a subset of any of the other Social Thematic Constructs. Parts of Nighttime go into all of social engagement food and bar, Infrequent social and Frequent social. - Left as Thematic for now but I don't have a strong preference.

**Comment by JanaHirsch** [comment]
@kam642 Seems good! Did I miss any others that should be moved to ComboCat from Thematic?

**Comment by JanaHirsch** [comment]
@kam642 basically I'm still torn about whether the thematic constructs should be 1) groups with no group above them OR 2) groups that are actually themes we conceptualized. For many groups this is the same but for others it isn't. I think the ones you listed are kind of themes (often we made them for set projects-- alcohol for Mariana, Marijuana for Andrew, Emergency for Yvonne/my disaster stuff).

**Comment by JanaHirsch** [comment]
We discussed this in our Jana/Stevphens meeting (@stfran22 @sd-drexel @sjmelly). We decided that for something to be a thematic construct it needs to be in a theme researched. 

**Please add to thematic constructs (from ComboCats):**
-All Financial Institutions
-All Alcohol Outlets
-Firearm-related stores and activities
-Marijuana farm production or dispensaries
-Emergency or Safety Services and Stations

**Comment by kam642** [comment]
@JanaHirsch Updated in the version of file I'm working on. I still have a few things to add for the comparisons w/RECVD and MESA then should be ready.

**Comment by JanaHirsch** [comment]
@kam642 what is the status of this? JHS was hoping for a NETS update for their next meeting.

**Comment by kam642** [comment]
@JanaHirsch Attaching the current working draft here. All the categorization and assignment to base, combo, thematic is done. I'm just doing some clean up and adding RECVD and MESA info for comparison purposes.

[NETS_Catalogue_ 3LTR_Variables_20230323_working.xlsx](https://github.com/Drexel-UHC/NETS/files/11390212/NETS_Catalogue_.3LTR_Variables_20230323_working.xlsx)

What is done:
-NETS_Catalogue_3LTR_Code worksheet
-Hierarchy worksheet
-Current Matrix worksheet
-RECVD Matrix worksheet
-MESA Matrix worksheet
-SIC codes worksheet: Codes for current and RECVD categories are done.

Left to do:
-I need to update the Introduction worksheet. I haven't touched that yet. Was waiting until everything else is done.
-SIC Codes worksheet: need to add MESA codes and check that the RECVD spot checks are marked as "yes" in "have spot check"
-Codebook_SIC Codes: needs to be updated when everything is added to the SIC Codes worksheet
-ConditionalCodeConditional worksheet: Not sure if we still need this. I'll check with Stevie.

**Comment by kam642** [comment]
@stfran22 @JanaHirsch I think I finished what I need to do on the excel file for now.

@stfran22 Can you do the following?
In Introduction:
-Double check that I can count and the numbers in rows 10-20 are correct.
-Read the description I added to describe the worksheets in rows 36-44. Edit or send me comments if they don't make sense.

In NETS_Catalogue_3LTR_code
-Update columns H, J, K, L, M, N as needed

In ConditionalCodeConditional
-Do we still need this worksheet? If so, can you complete this?

In Codebook_SIC Codes
-Review the definitions to make sure they make sense. Edit or send me comments if they don't make sense.


@JanaHirsch Can you do the following?
-Review the tips in "introduction" lines 26-32. Not sure all of this is still relevant.

[NETS_Catalogue_3LTR_Variables_20230516.xlsx](https://github.com/Drexel-UHC/NETS/files/11489822/NETS_Catalogue_3LTR_Variables_20230516.xlsx)

**Comment by stfran22** [comment]
@kam642 sorry for the delay. Here are my responses/updates:
 
> @stfran22 Can you do the following? In Introduction: -Double check that I can count and the numbers in rows 10-20 are correct. 

I see only 3 BaseGroups in the Transportation Domain, and a total of 184 BaseGroups. Corrected in version 20230615. All else is correct. 

>-Read the description I added to describe the worksheets in rows 36-44. Edit or send me comments if they don't make sense.

Changes made in version 20230615: 
- deleted row for Conditional Code sheet. Sheet not necessary in this document.
- Cell C42: changed "..base categories that are..." to "...base groups that are..."

> In NETS_Catalogue_3LTR_code -Update columns H, J, K, L, M, N as needed

Column H completed in version 20230615.

I propose deleting columns J,K, and L (Condition_Code, Condition_Code_Comments, and Code_Differences), which I have done in version 20230615. We may want to keep the latter two in a separate doc, but the only reason we would need them is to do a check on the previous Business Categorization process (using NETS 2014?). We were making note when the code from the auxiliary category configuration file given to us by Jesse did not match the NETS_Catalogue_3LTR_Variables doc.

@kam642 For columns M, N - what are the criteria for being "updated"? Does this only include a changed technical definition, or does a changed domain count? Not yet updated. This should be the only thing not addressed from your previous comment.

> In ConditionalCodeConditional -Do we still need this worksheet? If so, can you complete this?

If this is to be a client-facing document, I can keep it elsewhere. It is only for coding purposes. Sheet has been deleted in new version.

> In Codebook_SIC Codes -Review the definitions to make sure they make sense. Edit or send me comments if they don't make sense.

Changes made in version 20230615:
- all instances of "base category" changed to "base group"

Rows 115-173: are MESA Codes 1-4 referring to old MESA code? Should we indicate that it is the old code/differenct MESA study somehow?

@kam642 @JanaHirsch  Last thoughts: 
- should we change any instance of SIC Code to just SIC?
-

**Comment by kam642** [comment]
@stfran22 
I still see the columns Condition_Code, Condition_Code_Comments, and Code_Differences in the 20230615 version. I think it's fine to delete these. I would recommend keeping them in another programming document.

For the column "updated" - good question. I didn't add that column so I'm not sure how it was being used. @JanaHirsch Should we keep the updated column and indicate if there are any differences between the RECVD version and our new version? I think that would be the best use of that if we keep it. And the "new" column included to indicate any new categories added?

Yes - the MESA Codes 1-4 were from previous MESA Neighborhood. I added this to the description for them "THIS WAS FROM THE NETS CATEGORIZATION USED IN THE ORIGINAL MESA NEIGHBORHOOD STUDY, NOT THE CURRENT MESA NEIGHBORHOODS AND AGING STUDY." Now saved in 20230616 version.

I don't have a preference for SIC or SIC Code. SIC stands for "standard industrial classification" so it's not wrong either way. I'll let  @stfran22 and @JanaHirsch decide.

Note - I am (slowly) working on a file with some comparisons between the new, RECVD, and MESA categories for Brisa that can also be a useful document for this study. Brisa is getting some differences in model results between old MESA and RECVD versions of NETS that we're trying to understand.

**Comment by stfran22** [comment]
I deleted the Condition_Code, Condition_Code_Comments, and Code_Differences columns in the 20230616 version. I hadn't checked in a while, but for some reason I thought SIC = "standard industrial code". In that case, I don't care either way, I say let's just leave things as they are. I'll confirm with Jana at our meeting Thursday.

**Comment by JanaHirsch** [comment]
@stfran22 and @kam642 
Re: SIC code vs SIC, I prefer SIC code (Standard Industrial Classification Code).

@kam642 edits to the lines in introduction (some NOTES next to each edited section):

1. Refer to the Business Data Derived from NETS Technical Document for more information. _(NOTE TO KARI: we MAY make a visual MindMap or we MAY make a page "about the datasets" but for not we don't have them)_
2. Download the spreadsheet.  Filter for a Thematic Construct of interest in the Type column (e.g. domain: Physical Activity, Type: Thematic Construct).  
Note: some groupings and constructs are included in multiple domains, so it may be better to leave the domain column unfiltered. _(NOTE TO KARI: I think it might be worth considering getting rid of "domains" since many overlap and since there are a lot of people who miss things by filtering. For now we can leave but it is worth discussing)_
3. Review the Thematic Construct description (e.g. the row for the "All Physical Activity facilities" category, APA) _(NOTE TO KARI: I think this just needs a word editing)_
4. To review more detail about the contents of a Thematic Construct:
a. Take note of the 3-letter codes listed in the Technical Definition column			
b. Clear filter for domain and Type			
c. Under 3-LTR Code, filter to view the codes of interest, e.g. the Thematic Construct APA and its components: MUL, MPA, VPA
_(NOTE TO KARI: I think this just needs a word editing)_	






































































2. * The primary category for a business is assigned based on its standard industrial classification (SIC), and also according to the results of a word or name search. Searches employing key words or names from chain name lists were used to assign establishments to categories thought to better represent the establishment type, rather than relying on SIC code alone. For example, a “PIZZA HUT” with SIC code of 58120300 would be classified as “Fast Food – SIC code based definition (FFS)” based on SIC code, “Pizza (PIZ)” based on having the word pizza, and “Fast Food Quick Service (QSV)” based on Pizza Hut being included in the Technomics/R&I chain name list.

**Comment by kam642** [comment]
@JanaHirsch @stfran22  I made the edits above. Saved as NETS_Catalogue_3LTR_Variables_20230807.xlsx. Moved the older versions to Archive folder.

**Comment by JanaHirsch** [comment]
@kam642 sounds good- is this issue closed now?
